### ISSUE TITLE
Add an option to use a black & white menu bar icon

### ISSUE THREAD

**Issue by simonc** [remear/jewelrybox#100]
Most of the menu bar icons are black and white.
I would be cool to hav an option to use such an icon.

A bit like the Dropbox option "Use black and white menu bar icons"

**Comment by remear** [comment]
Done and added into the 1.3 release. Thanks for not only asking for feature, but also for providing the icon to help with implementing it.

**Comment by simonc** [comment]
Ok sorry, I didn't found the related issue :)
I didn't provide any picture because I didn't want to impose my idea of the icon to the project :)

Thank you !
