### ISSUE TITLE
Clear Logs

### ISSUE THREAD

**Issue by pboling** [remear/jewelrybox#103]
I just installed Jewelery Box, and was surprised to find that I have ~500MB of logs (1/2 of my installation).  I wouldn't know where to start to clean them up.  This would be a very useful feature!

**Comment by remear** [comment]
Yep. It's on our radar!

**Comment by pboling** [comment]
Wonderful!

**Comment by remear** [comment]
Related to #118 and will be addressed in that feature.

**Comment by remear** [comment]
This has been added and will be available in the next release. http://cl.ly/image/0i3S0F2Y302K

**Comment by pboling** [comment]
Bozarking awesome.
