### ISSUE TITLE
Failure to add any Ruby version other than 1.9.3

### ISSUE THREAD

**Issue by lottscarson** [remear/jewelrybox#104]
**OS** - Mac OS X 10.7.3
**Xcode/Developer Tools** - 4.2
**JewelryBox** - 1.2.1
**RVM** - 1.12.3

**Repro**:
1. Open JewelryBox
2. Click the "Add Ruby" button located in the upper-row of the window
3. Click on any ruby version earlier than 1.9.3
4. Click the "Install" button located in the right pane

**Actual Result**:
- The installer progress is eventually no longer visible
- Clicking another button (ie "Dashboard") and then again clicking "Add Ruby" does not refresh or re-initialize the view
- The following pertinent messages are displayed in /private//var/log/System.log:

`
Apr 17 22:26:24 Scotts-MacBook-Pro JewelryBox[89774]: 1
Apr 17 22:26:25 Scotts-MacBook-Pro [0x0-0x22ab2a9].com.unfiniti.JewelryBox[89774]: bash: no job control in this shell
Apr 17 22:26:40: --- last message repeated 4 times ---
Apr 17 22:26:40 Scotts-MacBook-Pro JewelryBox[89774]: Could not find image named 'tab_item'.
Apr 17 22:26:54 Scotts-MacBook-Pro [0x0-0x22ab2a9].com.unfiniti.JewelryBox[89774]: bash: no job control in this shell
Apr 17 22:29:00: --- last message repeated 1 time ---
Apr 17 22:36:01 Scotts-MacBook-Pro [0x0-0x22ab2a9].com.unfiniti.JewelryBox[89774]: bash: no job control in this shell
Apr 17 22:36:31: --- last message repeated 1 time ---
Apr 17 22:38:06 Scotts-MacBook-Pro [0x0-0x22ab2a9].com.unfiniti.JewelryBox[89774]: bash: no job control in this shell
Apr 17 22:38:27: --- last message repeated 3 times ---
Apr 17 22:38:27 Scotts-MacBook-Pro JewelryBox[89774]: *** -[__NSCFString substringToIndex:]: Range or index out of bounds
Apr 17 22:38:27 Scotts-MacBook-Pro JewelryBox[89774]: (
        0   CoreFoundation                      0x00007fff8e288fc6 __exceptionPreprocess + 198
        1   libobjc.A.dylib                     0x00007fff872b2d5e objc_exception_throw + 43
        2   CoreFoundation                      0x00007fff8e288dfa +[NSException raise:format:arguments:] + 106
        3   CoreFoundation                      0x00007fff8e288d84 +[NSException raise:format:] + 116
        4   Foundation                          0x00007fff897b2aec -[NSString substringToIndex:] + 98
        5   JewelryBox                          0x000000010001a483 -[RubyInstallationEnd awakeFromNib] + 746
        6   AppKit                              0x00007fff87418b71 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 1311
        7   AppKit                              0x00007fff8753a24b -[NSNib instantiateNibWithExternalNameTable:] + 606
        8   AppKit                              0x00007fff87539fb8 -[NSNib instantiateNibWithOwner:topLevelObjects:] + 251
        9   AppKit                              0x00007fff875394ff -[NSViewController loadView] + 186
        10  AppKit                              0x00007fff875351da -[NSViewController view] + 41
        11  JewelryBox                          0x00000001000018c7 -[AddRubyViewController shouldChangeViewController:] + 1067
        12  Foundation                          0x00007fff89785d32 __-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_1 + 47
        13  CoreFoundation                      0x00007fff8e231aaa _CFXNotificationPost + 2634
        14  Foundation                          0x00007fff89771fe7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 65
        15  JewelryBox                          0x000000010001bb76 -[RubyInstallerViewController task:didCompleteWithStatus:] + 1251
        16  JewelryBox                          0x0000000100016b5f -[NSTaskHelper taskDataAvailable:] + 576
        17  Foundation                          0x00007fff89785d32 __-[NSNotificationCenter addObserver:selector:name:object:]_block_invoke_1 + 47
        18  CoreFoundation                      0x00007fff8e231aaa _CFXNotificationPost + 2634
        19  Foundation                          0x00007fff89771fe7 -[NSNotificationCenter postNotificationName:object:userInfo:] + 65
        20  Foundation                          0x00007fff8983e6c1 _performFileHandleSource + 1129
        21  CoreFoundation                      0x00007fff8e1f76e1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
        22  CoreFoundation                      0x00007fff8e1f6f4d __CFRunLoopDoSources0 + 253
        23  CoreFoundation                      0x00007fff8e21dd39 __CFRunLoopRun + 905
        24  CoreFoundation                      0x00007fff8e21d676 CFRunLoopRunSpecific + 230
        25  HIToolbox                           0x00007fff8350031f RunCurrentEventLoopInMode + 277
        26  HIToolbox                           0x00007fff835075c9 ReceiveNextEventCommon + 355
        27  HIToolbox                           0x00007fff83507456 BlockUntilNextEventMatchingListInMode + 62
        28  AppKit                              0x00007fff87406f5d _DPSNextEvent + 659
        29  AppKit                              0x00007fff87406861 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
        30  AppKit                              0x00007fff8740319d -[NSApplication run] + 470
        31  AppKit                              0x00007fff87681b88 NSApplicationMain + 867
        32  JewelryBox                          0x0000000100001344 start + 52
        33  ???                                 0x0000000000000002 0x0 + 2
    )
`
**Expected Result**:
- Ruby versions earlier than 1.9.3 should install successfully and be usable
- The installer progress should never become invisible or fail without presenting an error/warning to the user

**Comment by lottscarson** [comment]
Ah rats, I should have known to check the existing issues.  This is a duplicate of https://github.com/remear/jewelrybox/issues/92 .

**Comment by remear** [comment]
Version 1.3 will provide better feedback on the problem you're experiencing but your inability to install other Ruby versions is not something JewelryBox can fix for you. You have Xcode 4.2, which is clang based and does not have the regular gcc required to build older rubies. Please refer to rvm notes for more information on how to resolve this issue.

**Comment by lottscarson** [comment]
Excellent.  Thanks for the useful info.
