### ISSUE TITLE
GCC Info in Dashboard should show contents of $CC

### ISSUE THREAD

**Issue by jonathanbeebe** [remear/jewelrybox#106]
I have $CC set in my path to /usr/bin/gcc-4.2 (on OSX Lion with Xcode 4.2), and from my understanding, that is what will be used when I install a new Ruby, even from JewelryBox (correct me if I'm wrong).

I think the GCC info in the Dashboard should reflect the contents of the $CC variable, and fallback to the default GCC installed on the system if $CC is not set.

**Comment by remear** [comment]
RVM uses custom compiler detection. Unfortunately those methods are not exposed publicly yet. The best I can do, for now, is as I mentioned in #88, and have JewelryBox correctly inherit the shell environment and figure out which compiler is picked up first. In the future I hope to have time to add the ability to extensively check the availability of multiple compilers on the system.
