### ISSUE TITLE
Visual glitches in Add Ruby view

### ISSUE THREAD

**Issue by bytesplit** [remear/jewelrybox#113]
The install options are on a side panel which slides in after clicking a Ruby version. On my SL10.6.8 this box gets destroyed as soon as I start to scroll the list of Rubies.

**Comment by remear** [comment]
What JewelryBox version are you using?

**Comment by bytesplit** [comment]
1.2.1 as downloaded from the website.

**Comment by remear** [comment]
Would you please see if this is still an issue in the 1.3 beta that's near release. https://docs.google.com/open?id=0B7-mS4miSnyfYnljYThVZHgtWDg

**Comment by bytesplit** [comment]
Problem still occurs in 1.3 build 2124.

**Comment by mpapis** [comment]
I had the same issue, after scrolling just click any ruby and the view is refreshed.

**Comment by remear** [comment]
v1.3 is the last release that will officially support OS X 10.6 Snow Leopard. Users will need to move to Lion or Mountain Lion to continue to use JewelryBox.

**Comment by mpapis** [comment]
:(
