### ISSUE TITLE
pkg Installer Area

### ISSUE THREAD

**Issue by remear** [remear/jewelrybox#120]
Add an area to install rvm pkgs.

@mpapis, is there a way to determine which pkgs are installed?

**Comment by mpapis** [comment]
check `~/.rvm/config/packages` but I do not think it's the best way, you could be better with checking existence of library and header for each pkg.

**Comment by remear** [comment]
@mpapis Has a package checker or any other helpers been added to RVM in the last few months to help with this? Is there at least a list of available packages?

**Comment by mpapis** [comment]
@remear no there were no changes in this, it will be a lot better in rvm2 - in fact with railsinstaller we already use smf - so it's what it will ne:

```
sm pkg list           # show list of installed packages
sm readline install   # install package
sm readline uninstall # remove package
sm set list           # list all available extensions - not all of them have to be package related ... but certain sets are pure package sets
```

**Comment by remear** [comment]
Is there an RVM 2 roadmap / schedule?

**Comment by mpapis** [comment]
unfortunately not, we have started documenting the whole thing, but RVM1 efforts all the time stand in the way of it ... for example binary builds got introduced - `rvm help mount`.

**Comment by remear** [comment]
RVM now uses your preferred package manager to install the necessary dependencies for compiling rubies. A pkg manager should no longer be necessary.
