### ISSUE TITLE
Post Messages to Notification Center

### ISSUE THREAD

**Issue by remear** [remear/jewelrybox#122]

**Comment by jtmkrueger** [comment]
AWESOME!

**Comment by remear** [comment]
@jtmkrueger I'm trying to determine if anyone on 10.8 still uses growl or if they have moved completely to the Notification Center. Can you tell me if you still use growl on your Mountain Lion machine.

**Comment by jtmkrueger** [comment]
Not personally, but I know people who need hardware growler, so they're out there.

**Comment by remear** [comment]
This feature is now complete and will be available in the next release. The Notification Center is used on machines running 10.8 or newer. Growl is used for machines 10.7.x or older.
