### ISSUE TITLE
Loading gem details

### ISSUE THREAD

**Issue by Elendir** [remear/jewelrybox#126]
System : OSX Lion 10.7.4
Ruby : 1.8.7
RubyGems : 1.4.2 (due to some legacy code)

I manually installed ruby 1.8.7 because of the issue with LLVM compiler.
When I try to fetch details for a gem, JewelryBox just crashes.
Here is the dump :
http://pastebin.com/1k8VDXUf

**Comment by remear** [comment]
Which gem and version are you trying to examine?

Please provide as much detail as you can for steps to reproduce the issue.

**Comment by Elendir** [comment]
I installed JewelryBox (currently 1.3 Build 2156 / RVM 1.14.5) and added ruby 1.9.3-head.
Having some legacy code with the default OSX Ruby I tried to install 1.8.7 via JewelryBox, but I had this issue #92
So I installed 1.8.7 via the terminal using rvm install 1.8.7 --with-gcc=clang.
I also downloaded some gems (rails for instance), and when I relaunched JewelryBox, the 1.8.7-p370 was correctly displayed. 
When I click on a gemset, all the gems are also correctly displayed.
But when I click on any gem to see its details, the app crashes while displaying "Loading Gem Details" with the loading spinner.

Any gemset, any gem, only ruby 1.8.7
1.9.3 has no problem.
The only difference I see is the platform. 1.8.7 is x86-darwin-11 and 1.9.3 is x86_64-darwin-11.

**Comment by remear** [comment]
Any Ruby older than 1.9.3-p125 shouldn't be compiled with clang. Its a high likelihood that your installation of 1.8.7 isn't completely solid. I'd recommend you remove that Ruby and set your machine up as explained in #92 and use gcc to compile 1.8.7. RVM will use gcc by default if you have it installed correctly.

**Comment by Elendir** [comment]
Thanks a lot.
I removed 1.8.7, installed gcc with osx-gcc-installer, ran CC=/usr/bin/gcc-4.2 rvm install 1.8.7-p370 --enable-shared and it worked like a charm except a patch did not apply.
Error running 'patch -F 25 -p1 -N -f <"/Users/username/.rvm/patches/ruby/1.8.7/stdout-rouge-fix.patch"'
