### ISSUE TITLE
Monochrome menubar icon

### ISSUE THREAD

**Issue by rjp** [remear/jewelrybox#129]
Everything else in my menubar has a monochrome icon (either by default or by a preference selection). Jewelrybox stands out as a hideous clashing clunker with its bright red icon (which is also a bit bigger than the others for extra clashing.)

A preference for using a monochrome icon would be excellent. Shrinking the icon to fit with the rest of them would be doubly excellent.

**Comment by remear** [comment]
The preference for using a black and white icon was added a while ago. Just go to Preferences, Check "Use Black and White Menu Icon" and restart JewelryBox.

I agree, the icons need to be slightly smaller as it's larger than most other icons.

**Comment by rjp** [comment]
Whoops, completely missed that preference. Apologies. Now my menubar is lovely and monochrome, thanks.
