### ISSUE TITLE
Upgrade for retina displays

### ISSUE THREAD

**Issue by georgemckibbin** [remear/jewelrybox#132]
Would be great if this supported retina display levels of detail :D

**Comment by remear** [comment]
I don't have a retina display so I don't even know what doesn't look great on one. Screenshots would help.

**Comment by docwhat** [comment]
You don't need a retina display, just the [High Resolution Guidelines for OS X](https://developer.apple.com/library/mac/#documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Introduction/Introduction.html)

Quote:

> You don’t need a high-resolution display to start optimizing your app and testing the code. Quartz Debug has features you can use to make sure your app is working as expected. When things don’t work as expected, the troubleshooting section can help you figure out the issue.

I (and I suspect @cooliodoc) would be willing to test the updated application.  You can contact me at http://docwhat.org/email

A quick scan shows these things that need updating:
- The MenuBar icon needs a higher res. version.
- The toolbar icons need higher res. versions. (Dashboard, Manage Rubies, etc.)
- Dashboard:
  - The text in the legend ("Archives", "Repos", etc.) is fuzzy; don't render to an image, or if you must, double the image size and let the apple rendering magic scale it down if needed.
- The other images look okay, but could probably be doubled as well (About and the Update tabs).

If you think images would be helpful, I can send them.

**Comment by remear** [comment]
To be more clear, I don't have access to a machine with a retina display and I don't like releasing things I'm unable to test or have tested. So, since you're willing to test it out, when I get time I can work on producing hi-res graphics and invite those monitoring this issue to test the changes in a beta release.

**Comment by docwhat** [comment]
Sure, I got that.

I wasn't clear on my point, which is that (according to my understanding) you use the same code paths and the same images for retina and non-retina systems.  OS X then scales images and renders fonts for you.  Even rendering the Dashboard space usage legend would be the same, just scaled down on non-retina computers.

Still happy to test. :-)

Ciao!

**Comment by remear** [comment]
Update: I spent some time today "retinafying" the application.

### Completed

Main area icons
Disk usage meter container
Disk usage meter legend

### Remaining

Menu icon
Active area carrot
Dot images
Arrow right-left icons used in popovers
Ruby installation sidebar
Gemset copy button
Gem server button
Wipe gemset button

**Comment by remear** [comment]
This should now be complete and will be available in v1.4.

**Comment by remear** [comment]
@cooliodoc @docwhat You're welcome to test the v1.4 beta and see if anything still looks bad on a retina display. http://dl.dropbox.com/u/5676052/JewelryBox_v1.4_b1.zip
