### ISSUE TITLE
Growl Notifications

### ISSUE THREAD

**Issue by seanculver** [remear/jewelrybox#133]
Here are some details about my environment

OS X 10.7.3
Growl 1.2
Jewelry Box Version 1.3 Build 2156
RVM version 1.14.11

It should be apparent what is happening, I left my computer on over the weekend and this is what I came back to.

http://imgur.com/7vlle

Is it possible to know when a growl notification already exists and not spawn another one?

I'm only reporting this because I love the software so much. You make my life so much easier!

Cheers,
Sean

**Comment by seanculver** [comment]
Normally I would close them all by hand which is annoying but I can go into growl and click stop growl and start growl and all those messages disappear in two clicks.

**Comment by remear** [comment]
I'm currently not aware of any way in the Growl framework to determine if a notification from JewelryBox is currently on the screen. For now, you can option-click on one to close them all. You could also increase the update check duration every few days which should minimize the likelihood of seeing more than one on your screen.
