### ISSUE TITLE
Trying to install Ruby 1.9.3 on Mountain Lion

### ISSUE THREAD

**Issue by davesag** [remear/jewelrybox#134]
Installed JewelryBox fine and that in turn installed RVM fine.

Went to `Add Ruby` and added `Ruby 1.9.3 head` and it started out okay but then the panel just went grey and now JewelryBox just seems to be doing nothing.

I quit JewelryBox and ran it again and now under `Add Ruby` I get the list of Rubies to add; chose `1.9.3 head` again and again it got to the end of the download part then the panel went grey.

I guess I'll go back to the command line and see if I can install Ruby 1.9.3 that way.

**Comment by remear** [comment]
See #92. I worked on this a bit but nobody really tested the builds I was putting out.

**Comment by davesag** [comment]
I was able to `rvm install 1.9.3` in the Terminal just fine and now it shows up as an installed option in JewelryBox but I have the warning message `Ruby 'ruby-1.9.3-p194' was built using clang - but it's not (fully) supported, expect errors.` which doesn't fill me with confidence. I wonder what sort of errors I ought to expect.

**Comment by remear** [comment]
Some gems might not compile. httparty often segfaults. Things along those lines usually occur, although not always. Your mileage may vary.

**Comment by davesag** [comment]
:-) I guess I'll just suck it and see. Getting OT now I feel but thanks.
