### ISSUE TITLE
Unable to retrieve gem environment

### ISSUE THREAD

**Issue by ghost** [remear/jewelrybox#141]
I just  installed jewelrybox , and got my settings list for my current existing  RVM environment, (rubies, latest gemset) , but the going to the manage gemset window , I get an error message "unable to retrieve Gem Envieonment" .. Could not load gem environment information, the Ruby may not have installed properly ...

I am currently running fine via the Command Line ... I guess I don't have to reinstall everything ( Ruby and Gems) via jewelrybox ?... or should I ?

thanks for feedback

**Comment by remear** [comment]
I've sometimes seen gemsets or the gem environment get slightly messed up. I'm still not sure why that happens. The unable to retrieve gem environment message is more of a catch-all for when JewelryBox, for whatever reason, can't get an acceptable response back.

No, you shouldn't have to reinstall everything via JewelryBox for it to work correctly. It's designed to work in tandem with the command-line and not take over your entire RVM experience. It allows you to use the command-line and GUI respectively whenever you please.
