### ISSUE TITLE
Add capability to upgrade rubies

### ISSUE THREAD

**Issue by hron84** [remear/jewelrybox#153]
Please add a capability to migrate/upgrade from one ruby to another if they are in same main version.

E.g. today I received jruby 1.7.1 which is an upgrade of 1.7.0, however I could not do upgrade/migrate from UI.

**Comment by remear** [comment]
Rubies can now be upgraded from the Manage Rubies area. For now, it requires you install the new ruby first and the old ruby is removed during the upgrade. These are the limitations with RVM. I hope to make this more flexible in the future.
