### ISSUE TITLE
The installation stops pending overwrite confirmation

### ISSUE THREAD

**Issue by kiub** [remear/jewelrybox#156]
The installation stops pending confirmation, unable to overwrite ~ / .rvm/rubies/ruby-1.9.3-p327/bin/gem
With the following message: overwrite / Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/gem? (y / n [n])
![Screen Shot 2012-12-13 at 1 52 56 PM](https://f.cloud.github.com/assets/1074882/10553/13a35a6a-4524-11e2-87d9-d1a34e43bda3.png)

Given this, continue the installation manually from terminal, and another series of confirmations are to be keep in mind:
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/gem? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/gem? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/irb? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/irb? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/erb? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/erb? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/ri? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/ri? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/rdoc? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/rdoc? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/testrb? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/testrb? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/rake? (y/n [n]) y
overwrite /Users/kiub/.rvm/rubies/ruby-1.9.3-p327/bin/rake? (y/n [n]) y

**Comment by mpapis** [comment]
what version of rvm was it?

**Comment by kiub** [comment]
rvm 1.17.2 (stable)

**Comment by mpapis** [comment]
try after `rvm get head`  -> https://github.com/wayneeseguin/rvm/commit/b5d25c745fa00daf63d77e59de283e2326f62b6e

**Comment by remear** [comment]
@kiub Is this resolved for you?

**Comment by kiub** [comment]
Sorry but I continued the installation via terminal following other instructions. I'll try again with a new version of Ruby, but for now it is not necessary.

**Comment by lmhaskins** [comment]
Happened to me when I updated Ruby to 1.9.3-p362... waiting for confirmation to overwrite gem.  Killed JewelryBox to move on with life.  JB version 1.4, build 1454.

This was after I updated rvm via JewelryBox.  If I do a 'rvm -version' it says:

A RVM version 1.17.7 is installed yet 1.10.3 is loaded.
 Please do one of the following:
- 'rvm reload'
- open a new shell

I'll forgo further updating if you need more info.

**Comment by remear** [comment]
@lmhaskins Please open a new issue at https://github.com/wayneeseguin/rvm so @mpapis can work with you on this.

**Comment by mpapis** [comment]
@remear is right, @lmhaskins please open an issue for RVM - thanks.
