### ISSUE TITLE
Unable to install jruby on OSX 10.8 due to improper $JAVA_HOME

### ISSUE THREAD

**Issue by yusefnapora** [remear/jewelrybox#157]
This isn't a JewleryBox issue per se, but it affects JewelryBox users, so I though I'd mention it.  Trying to install jruby via JewelryBox gives the following errors:
    /Users/yusefnapora/.rvm/rubies/jruby-1.7.1/bin/ruby: line 388: /System/Library/Frameworks/JavaVM.framework/Home//bin/java: No such file or directory
    /Users/yusefnapora/.rvm/rubies/jruby-1.7.1/bin/ruby: line 388: exec: 
    /System/Library/Frameworks/JavaVM.framework/Home//bin/java: cannot execute: No such file or directory
    mkdir: /gems: Permission denied

This is due to OSX Lion and above not setting the JAVA_HOME environment variable correctly. By default (on my system anyway, I think it's universal) JAVA_HOME is set to /System/Library/Frameworks/JavaVM.framework/Home - it should be set to the output of the /usr/libexec/java_home command.

In a terminal, you can 
      export JAVA_HOME=$(/usr/libexec/java_home)
and then `rvm install jruby` but so far I haven't been able to figure out how to set JAVA_HOME for GUI apps.  (editing /etc/launchd.conf doesn't seem to work)

Anyway, you might consider setting JAVA_HOME to the output of /usr/libexec/java_home before installing jruby.

**Comment by remear** [comment]
You might want to report this in http://github.com/wayneeseguin/rvm/issues so it is fixed at the RVM level. They'll also work with the jruby team to fix it the way the jruby team recommends.

**Comment by yusefnapora** [comment]
Nevermind!  Sorry about this - I apparently had mucked about with my JAVA_HOME in my zsh profile earlier which was causing this.  Oops.
