### ISSUE TITLE
Global Cache button/action inconsistent

### ISSUE THREAD

**Issue by rbq** [remear/jewelrybox#158]
If I click the button to **enable** the global cache it says: **Disabling** gemset global cache. (And the other way round.) I tried to find out which of the two outputs describes what's actually happening but couldn't figure out how to use the CLI (e. g. `rvm gemset globalcache enable`) diesn't work.

**Comment by remear** [comment]
I believe the button behavior is correct and the loading indicator message is flipped. I'll get this queued for a fix release.

Enabling/disabling gemset globalcache is as simple as `rvm gemset globalcache enable` or `rvm gemset globalcache disable`

Checks are performed with `rvm gemset globalcache enabled`

**Comment by remear** [comment]
This should be fixed in v1.4.1
