### ISSUE TITLE
RVM 1.17.3 installed but JB doesn't see it

### ISSUE THREAD

**Issue by dborin** [remear/jewelrybox#159]
Continually being prompted to do a 1.17.3 RVM update upon starting JB, but it is installed and from the command line:

$  rvm --version

rvm 
1.17.3 (
stable) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

JB is disabled until it gets the update.  Not sure how to make it "see" it

**Comment by remear** [comment]
I'm not really sure what's going on here. I just upgraded a 1.3 build to 1.4 on a machine that already had 1.17.3 (stable) on it and it worked without issue.

Have you already tried doing `rvm get stable` again from the command-line?

**Comment by remear** [comment]
And to clarify, I also relaunched that same application several times and it brought up the dashboard just fine.

**Comment by dborin** [comment]
Bill,

In your case, you already had 1.17.3 installed.  What happened to me was:

1) Fired up JB -- Says that I can upgrade JB, so I upgrade JB.
2) Relaunched JB says it requires RVM 1.17.3 or higher, so I click on the Upgrade button in the JB GUI
3) Upgrading RVM using JB fails
4) Go to command line and do "rvm get stable" and "rvm relaunch" and that upgrades RVM

After that JB would not "see" the 1.17.3, even tho my .bashrc and .bash_profile are all setup correctly, and I even restarted my Macbook.

**Comment by dborin** [comment]
Any additional information needed or available on this?  I'd really love to be able to use JB again.  If not, how does one completely remove JB and any environment files associated with it?  Seems like just removing JB doesn't fix the problem upon reinstall.  Wondering if there's a plist or other such file on my Macbook causing the problem, that I can remove.

**Comment by dborin** [comment]
Here's a short Flash movie of what I'm seeing http://screencast.com/t/RkHDGkvFaC

**Comment by remear** [comment]
Can you record a new screencast of what happens when you run `rvm version`  You specified --version. Normally they output the same but on all of my machines it's output in a single line but yours seems to output on two. Mine looks like `rvm 1.17.7 (stable) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]`

**Comment by dborin** [comment]
It looks exactly the same (actually three lines) whether or not I use version, -v or --version

**Comment by remear** [comment]
You're correct. I meant to say three lines. I'm mostly sure that's what is causing it to not find your installation. I've not seen this issue reported to the RVM team but I have to say that I suspect something in your shell setup is breaking that output into multiple lines. I suggest opening an issue over at https://github.com/wayneeseguin/rvm so @mpapis can help you track down why that might be happening.

**Comment by dborin** [comment]
Gar...that is wonky, but thanks for finding that.

**Comment by remear** [comment]
Let me know the outcome. And sorry about the delayed response, holidays and work backlog =/

**Comment by dborin** [comment]
I'd done some things with aliasing a while back and didn't change them back.  I'd aliased "cat" to put a line before it dumped the contents of whatever was being catted, and apparently that messes up the version display.  Removing that seems to fix the version output.

**Comment by dborin** [comment]
Forgot to mention that it fixed the problem too

**Comment by remear** [comment]
Excellent! Have fun with v1.4 and please report any other issues you may find.
