### ISSUE TITLE
Version 1.4 incompatible with Snow Leopard, but the updater still allowed me to install it

### ISSUE THREAD

**Issue by reger** [remear/jewelrybox#160]
Seems like it should check and not allow me to install it.  There's nothing in the Changelog that indicates Lion is required to run it either. How do I get back to 1.3?

**Comment by remear** [comment]
It's supposed to =/  I just altered the checking so it shouldn't allow upgrading anymore. The last version compatible with 10.6 will be up on the site by tomorrow. Keep in mind though that you'll have to downgrade your RVM to probably around RVM 1.16. JewelryBox 1.3 won't work with anything much newer than that.

**Comment by rupe** [comment]
I've been using RVM 1.17.2 and Jwelerybox (last version that worked with SL) on my SnowLeopard system without any problems ... at least any known problems. Is there some reason why you say RVM 1.16 should be used?

Also, I just selected update, without any notification that 10.7 or newer was needed, so had to search for an archived version to use. As I have no plans, or reason, to move to Lion/Mountain, I guess this will be the final version for me :(

**Comment by remear** [comment]
#155, for one. It will probably crash because RVM changed the way it listed gemsets. There are various other small things like that. Just find an RVM version that works well for what you're doing with JewelryBox and stick with it.

**Comment by rupe** [comment]
Hmmm. From Jewelerybox's About screen: Jewelerybox version 1.3 build 2156, RVM version 1.17.2. I have never had a crash, so I guess guess this is what I'll be sticking with.

Maybe someone will fork JB to keep a Snow Leopard compatible version going :)
