### ISSUE TITLE
RVM Usage graph incorrectly represents Gemsets as Logs

### ISSUE THREAD

**Issue by bradland** [remear/jewelrybox#164]
OS: OS X 10.8.2
JewleryBox version: 1.4.1.1462
RVM Version: 1.17.9

When viewing the Dashboard, Overview screen, the graph near the bottom uses the yellow color assigned to Logs to represent Gemsets. You can see from the output below that I only have 16K of log files, but 2 GB of gemsets.

**Dashboard > Overview**

![dashboard-overview](https://f.cloud.github.com/assets/2764/73303/5609c24a-603b-11e2-9509-c7aef8d541ae.png)

**Dashboard > Disk Usage**

![dashboard-disk-usage](https://f.cloud.github.com/assets/2764/73302/43f3603e-603b-11e2-8f23-0ed8b941cb89.png)

**Preferences**

![preferences](https://f.cloud.github.com/assets/2764/73305/67ba8556-603b-11e2-9eeb-6c38576aa361.png)

Output of `rvm disk-usage all`:

```
bradland@macbookpro:~$ rvm disk-usage all
   Downloaded Archives Usage: 157M
          Repositories Usage: 0B
 Extracted Source Code Usage: 738M
             Log Files Usage: 16K
              Packages Usage: 624K
                Rubies Usage: 237M
               Gemsets Usage: 2.0G
              Wrappers Usage: 1.8M
       Temporary Files Usage: 0B
           Other Files Usage: 8.0M
            Total Disk Usage: 3.1G
```

**Comment by remear** [comment]
This is now fixed in v1.4.2. Expect it to drop soon.

**Comment by bjansen** [comment]
It's been two months now, can we expect v1.4.2 soon? Thanks :)

**Comment by remear** [comment]
v1.4.2 was ready to go, then the RVM team introduced a bunch of major changes that required updates in JewelryBox.

v1.5 should now be available. Thanks for your patience.
