### ISSUE TITLE
Confusing statements regarding compatible versions of rvm.

### ISSUE THREAD

**Issue by slothbear** [remear/jewelrybox#165]
I heard about Jewelry Box yesterday and thought I'd give it a try. When I got to the site, I found this info:

```
Current Version: 1.4.1

10.6 is no longer supported. Download v1.3 here. 
Does not work with newer versions of RVM. Use RVM ~1.16.x
```

I thought both of the lower lines were describing Jewelry Box 1.4.1. Since I'm using a newer version of RVM (1.17.8), I figured I could not use Jewelry Box.

Thinking about it later, it didn't make sense that the official GUI lacks support for the current RVM. I figured there would be plans to support newer versions of RVM, so I checked the _Roadmap_. The v1.4 Changelog says there is already _Compatibility with newer RVM versions_.

Now I realize that the statement `Does not work with newer versions of RVM` refers to v1.3 in the previous line, not v1.4. Perhaps not many people make my mistake, but it would be great if each statement mentioned explicit versions. Perhaps something like this:

```
v1.4 does not support Mac OS X 10.6. Download v1.3 here. 
v1.3 not work with RVM ~1.17.x. Use RVM ~1.16.x
```

In the Roadmap/v1.4 Changelog section, add an explicit version, perhaps:

```
- Compatability with RVM 1.17 (or whatever the compatible versions are)
```

Ok, now I'm off to try Jewelry Box. It looks great!

**Comment by dwormuth** [comment]
When can we expect Jewelrybox to support the current RVM?

**Comment by remear** [comment]
For OS X 10.7 or newer, it already supports the latest version apart from the verify downloads issue that will be fixed shortly. Is something not working fir you? If you encounter problems that aren't already reported here on github, please open new issues for them.

For OS X 10.6, never. It's end-of-life. Use version 1.3 and download 1.16.x

**Comment by dwormuth** [comment]
Apparently I was mistaken, I seemed to have a crasher on jewelrybox startup. I can't seem to recreate it now. 

David W. Wormuth
dwormuth@post.harvard.edu

**Comment by EthanMichaels** [comment]
Hi remear. I too find the text on http://jewelrybox.unfiniti.com totally confusing.

It says "does not work with newer versions of RVM," yet above you're saying it does do so.

Something like this on your website would be a huge help...

[**Jewelry Box** `1.4.x`]() runs on **Mac OS** `10.[?]` to `10.[?]` and works with **RVM** `[?]` to `[?]`.

[**Jewelry Box** `1.3.x`]() runs on **Mac OS** `10.[?]` to `10.[?]` and works with **RVM** `[?]` to `[?]`.

**Comment by slothbear** [comment]
I like @jarron positive requirements instead of my suggestions, which said things like "does not support".

**Comment by slothbear** [comment]
Here's an example I liked, with different download buttons for each version, all stated in the positive form: http://pqrs.org/macosx/keyremap4macbook/pckeyboardhack.html.en

**Comment by remear** [comment]
Positive statements as mentioned often give the impression that the older version is still maintained. That isn't the case here. We're leaving OS X 10.6 support behind and providing a link to the last version that reliably runs on 10.6 as a courtesy.

The wording should now be updated on http://jewelrybox.unfiniti.com to be much more clear.
