### ISSUE TITLE
Crash on YAML install

### ISSUE THREAD

**Issue by jorisvh** [remear/jewelrybox#167]
Just after displaying the message about Yaml being installed, the application becomes completely grey (I just see the menu with Dashboard, Manages rubies, etc.)

**Comment by remear** [comment]
Which ruby version were you installing?

**Comment by jorisvh** [comment]
Sorry, after installing this: https://github.com/kennethreitz/osx-gcc-installer/ it works ! Actually I found that in the closed bugs. Sorry again !

**Comment by remear** [comment]
Actually, your filing of this issue helped me find 2 bugs users may or may not be experiencing. One has to to with RVM halting installations when it can't verify downloads. The other is a logic error for detecting log file paths in the output because not every occurrence of "Please read" is followed by a log path. The logic fails when it says things like "Please read 'rvm mount' ...". I'll be fixing these issues for the next update. I'll leave this issue open until that time.

**Comment by CaptainFatty** [comment]
Trying to install any version of ruby (currently running matz 1.8.7) with jewelryBox 1.4.1 build 1462 rvm 1.18.6, osx 10.8.2. Same issues as jorisvh. Latest Xcode installed so unwilling to use the osx-gcc-installer. All I wanted to do is get ruby tk working again...:( Here is output from console:

16/02/2013 09:35:11.049 JewelryBox[84825]: **\* WARNING: -[NSImage compositeToPoint:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
16/02/2013 09:35:11.051 JewelryBox[84825]: **\* WARNING: -[NSImage compositeToPoint:fromRect:operation:] is deprecated in MacOSX 10.8 and later. Please use -[NSImage drawAtPoint:fromRect:operation:fraction:] instead.
16/02/2013 09:35:34.053 JewelryBox[84825]: Could not find image named 'arrow_right_grey_dark25x25'.
16/02/2013 09:35:34.060 JewelryBox[84825]: **\* -[**NSCFString substringToIndex:]: Range or index out of bounds
16/02/2013 09:35:34.067 JewelryBox[84825]: (
    0   CoreFoundation                      0x00007fff926020a6 __exceptionPreprocess + 198
    1   libobjc.A.dylib                     0x00007fff901273f0 objc_exception_throw + 43
    2   CoreFoundation                      0x00007fff92601e7c +[NSException raise:format:] + 204
    3   Foundation                          0x00007fff96c32909 -[NSString substringToIndex:] + 97
    4   JewelryBox                          0x0000000104e9fe04 JewelryBox + 171524
    5   AppKit                              0x00007fff95f11258 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 1234
    6   AppKit                              0x00007fff96127a66 -[NSNib _instantiateNibWithExternalNameTable:] + 610
    7   AppKit                              0x00007fff961277d3 -[NSNib instantiateNibWithOwner:topLevelObjects:] + 254
    8   AppKit                              0x00007fff96126d87 -[NSViewController loadView] + 184
    9   AppKit                              0x00007fff960cebe9 -[NSViewController view] + 41
    10  JewelryBox                          0x0000000104e783be JewelryBox + 9150
    11  CoreFoundation                      0x00007fff925b447a _CFXNotificationPost + 2554
    12  Foundation                          0x00007fff96c1b846 -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
    13  JewelryBox                          0x0000000104ea1d64 JewelryBox + 179556
    14  JewelryBox                          0x0000000104ea13ff JewelryBox + 177151
    15  JewelryBox                          0x0000000104e9dcb3 JewelryBox + 162995
    16  CoreFoundation                      0x00007fff925b447a _CFXNotificationPost + 2554
    17  Foundation                          0x00007fff96c1b846 -[NSNotificationCenter postNotificationName:object:userInfo:] + 64
    18  Foundation                          0x00007fff96cd9a7c _performFileHandleSource + 1280
    19  CoreFoundation                      0x00007fff92581101 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** + 17
    20  CoreFoundation                      0x00007fff92580a25 __CFRunLoopDoSources0 + 245
    21  CoreFoundation                      0x00007fff925a3dc5 __CFRunLoopRun + 789
    22  CoreFoundation                      0x00007fff925a36b2 CFRunLoopRunSpecific + 290
    23  HIToolbox                           0x00007fff8f1db0a4 RunCurrentEventLoopInMode + 209
    24  HIToolbox                           0x00007fff8f1dae42 ReceiveNextEventCommon + 356
    25  HIToolbox                           0x00007fff8f1dacd3 BlockUntilNextEventMatchingListInMode + 62
    26  AppKit                              0x00007fff95f50613 _DPSNextEvent + 685
    27  AppKit                              0x00007fff95f4fed2 -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 128
    28  AppKit                              0x00007fff95f47283 -[NSApplication run] + 517
    29  AppKit                              0x00007fff95eebcb6 NSApplicationMain + 869
    30  JewelryBox                          0x0000000104e77bc4 JewelryBox + 7108
    31  ???                                 0x0000000000000002 0x0 + 2
)

Cheers,
CaptainFatty

**Comment by remear** [comment]
#173
