### ISSUE TITLE
Wrong Ruby version interpreter

### ISSUE THREAD

**Issue by ChristoRibeiro** [remear/jewelrybox#168]
Hi, 
I installed ruby-2.0.0-rc2 without problem, but in my zsh shell I still have the 1.8.7 version for the ruby interpreter. To switch to the version to 2.0.0-rc2,  I have to run 

``` bash
rvm use 2.0.0-rc2 --default 
```

 after that, ruby -v give me the good ruby version.

I have to do something with my .zshrc after installing a new version of ruby ?

**Comment by remear** [comment]
Does PATH in your .zshrc  look like PATH=$PATH:....

RVM has some issue that requires "$PATH" to be in your path var. Other issues might include the use after install option not being checked when you installed the ruby or not selecting it from the menu to make it the default ruby. 

Let me know if the issue persists after you've checked these.

**Comment by ChristoRibeiro** [comment]
In fact my symlinks in /usr/bin was wrong. I updated the symlinks to the bin folder of rvm, and now it works. Thank for your quick answer

**Comment by remear** [comment]
I'm not sure what you're symlinking since that shouldn't be necessary, but I'm glad it's now working for you.

**Comment by ChristoRibeiro** [comment]
in reality I added $HOME/.rvm/bin in begin of my PATH :)
