### ISSUE TITLE
First time install, crashes on launch

### ISSUE THREAD

**Issue by shellbryson** [remear/jewelrybox#176]
First-time install on brand new MacBook. Install app, prompted to install RVM. Appeared to crash during process, or just after. Now whenever application launched, immediately crashes, no message.

**Comment by ghost** [comment]
same here, install, first run, install rvm, next launch crash over again

https://gist.github.com/jimiii/5058969

**Comment by remear** [comment]
Attaching gists containing the crash reports would be helpful. You can obtain them from Console.app.

**Comment by ghost** [comment]
updated, xcode reinstall solves problem for me

**Comment by remear** [comment]
I just ran through a fresh install of RVM via JewelryBox using v1.5 but didn't experience a crash. Can you give it a try. https://www.dropbox.com/s/wamz01vxbr1g36m/JewelryBox_v1.5_beta.zip

**Comment by JoshuaRogers** [comment]
Had the same problem. Resolved it by installing XCode Console Line Tools. I'm guessing it was because 'make' was missing.

**Comment by remear** [comment]
#180 Crashes when no gcc is installed. The output when the gcc command is not found breaks the array length.

**Comment by remear** [comment]
Should now be resolved in v1.5
