### ISSUE TITLE
Non-Admin User

### ISSUE THREAD

**Issue by henri** [remear/jewelrybox#185]
Hello,

Firstly, this project is just great!

One thing which may be worth testing against is the ability to run JewelryBox from a standard account (not an administrator). To date I have been unsuccessful. However, that could be because I have MacPorts installed. I will carry out some additional testing. In the mean time if you have confirmed that it will work as a non-admin user then please let me know. If you are not testing for this setup then perhaps (if feasible) it is worth considering.

**Comment by remear** [comment]
JewelryBox is supposed to work in both single-user and multi-user setups. I personally extensively test in the standard single-user setup. I used to test a lot against dependencies I compiled myself and MacPorts, but over the past year I've moved to using homebrew for managing my dependencies.

RVM has recently taken to using package managers to install dependencies Ruby needs to successfully compile and run. On OS X RVM should support MacPorts, Fink, and homebrew. Make sure to click "Requirements" in the dashboard view to check if your dependencies are met. If they aren't, information should be displayed on what you can do to satisfy them. This is known as the new autolibs feature of RVM.

**Comment by henri** [comment]
Thank you for your prompt reply.

The requirements tab displays the following message : 

"
RVM requirements
Installing requirements for osx, might require sudo password.
"

I am currently testing with HomeBrew and will let you know how I get on.

Good to know that the idea is to support standard users as well as Administrators.

Thank you again. I will keep you updated.
