### ISSUE TITLE
intall ruby 2.0 and get the error required smf

### ISSUE THREAD

**Issue by yangyraaron** [remear/jewelrybox#188]
the ruby version that i attempt to install is ruby-2.0.0-po,and i got the error is follow

Installing requirements for smf, might require sudo password.

Updating SMF.

Error running 'requirements_smf_update_system',

my system is mac osx 10.8.3

**Comment by remear** [comment]
You can try going to Dashboard -> Requirements and wait for a while (it might take a really long time). If it never works you might need to adjust RVM autolibs.

I would advise you to join IRC #rvm and have someone help you get your dependency issues via SMF resolved and give you some help with RVM autolibs.

**Comment by yangyraaron** [comment]
thanks,i have solved the problem,it needs to change some rvm configuration files.

**Comment by eneskaya** [comment]
Would be very nice if you could explain your solution, having the same problem over here.

**Comment by yangyraaron** [comment]
ok, i follow this post http://stackoverflow.com/questions/12928581/problems-installing-ruby-on-mountain-lion-ruby-1-9-3-wont-compile on stackoverflow and fix the problem.
hope it help.
