### ISSUE TITLE
How do I uinstall jewelrybox from mac osx?

### ISSUE THREAD

**Issue by gunix28** [remear/jewelrybox#189]
I am just no longer interested in Ruby so it has nothing to do with your software.

**Comment by remear** [comment]
Drag JewelryBox.app to the trash.
Remove ~/Library/Preferences/com.unfiniti.JewelryBox.plist
Remove RVM if you haven't already (open your Terminal and run rvm implode)

**Comment by devinrhode2** [comment]
If I just want to remove JewelryBox, do I need to touch RVM at all?
