### ISSUE TITLE
Error creating/modifying /opt/local/etc/openssl/cert.pem during clean install

### ISSUE THREAD

**Issue by jessefulton** [remear/jewelrybox#198]
From a clean install and new OSX user, I tried installing ruby-2.0.0-p247 and received the following error:

"Updating certificates in '/opt/local/etc/openssl/cert.pem'. sudo : no tty present and no askpass program specified"

It installed via command line, but I was prompted to enter my password at the following:

```
jessefulton password required for 'mv -f /var/folders/4h/1vqvnhf94qs4fpgjltwk0vyc0000gq/T//tmp.YSVYdPJio19jRR19gh /opt/local/etc/openssl/cert.pem': 
```

**Comment by remear** [comment]
JewelryBox currently does not support prompting for a password to gain sudo access. You need to do such things from the command line for now.
