### ISSUE TITLE
Newer version of RVM available; JB 1.5 not showing RVM Update button

### ISSUE THREAD

**Issue by AnubisKB** [remear/jewelrybox#201]
I have rvm 1.20.9 (stable) installed but I know there is at least 1.24.x (stable) available. JewelryBox is at version 1.5 (newest) and it is not prompting me for the RVM upgrade.

1) Is this a bug and will it be fixed?

2) Can I just update RVM at the command line safely?

**Comment by remear** [comment]
1) Could be. I'll look into it when i have some time.

2) Yes, assuming the new version of RVM doesn't break anything JewelryBox expects (output format changes and such)

**Comment by AnubisKB** [comment]
Ok thx! :-)

**Comment by AnubisKB** [comment]
I manually updated RVM and that worked so we'll see if it shows button next time RVM update is available and I'll let you know - thx again
