### ISSUE TITLE
ruby-1.9.3-p448 missing from MRI Rubies install list

### ISSUE THREAD

**Issue by AnubisKB** [remear/jewelrybox#202]
The list jumps from -p429 to -head. Shouldn't -p448 be in the list? Can I install it manually and have it work with JB?

**Comment by remear** [comment]
The list of available rubies comes directly from RVM. None of them are hard-coded. Would you compare the output of the # MRI Rubies section from `rvm list known` and see if it's the same as what you see in JewelryBox.

JewelryBox is basically just an interface to the RVM command line. You should, as a rule, always be able to do stuff in either RVM on the command line or in JewelryBox without conflict.

**Comment by AnubisKB** [comment]
ok thx - I'll take a look at what you suggested

**Comment by AnubisKB** [comment]
I updated RVM and that worked fine - I see that dvm list known did update - so hopefully with this update everything will start working. I only see 1.9.3-p484 btw so I'm guessing older versions are no longer supported or recognized?
