### ISSUE TITLE
Incorrect gemsets listed

### ISSUE THREAD

**Issue by mphstudios** [remear/jewelrybox#205]
After a system restart "Using /Users/mph/.rvm/gems/ruby-2.0.0-p353" and "Using /Users/mph/.rvm/gems/ruby-2.1.0" are listed as gemsets under Ruby-1.9.8-P484 and Ruby-2.0.0-P353 though empty and without Gem Environment information (see screen image).

![jewelrybox gemset bug](https://f.cloud.github.com/assets/203339/1819087/704d9de6-705e-11e3-9567-aefccd7b226a.png)

**Comment by remear** [comment]
Looks like the RVM guys once again decided to change the output formatting. I'll work on this when I can find a block of open time.
