### ISSUE TITLE
installation failed with status: 1

### ISSUE THREAD

**Issue by wdonovan12** [remear/jewelrybox#208]
i am running osx 10.8.5, with xcode 5.0.2

trying to install ruby with the following options
https://www.dropbox.com/s/qevavegyiu2rlex/Screenshot%202014-01-09%2010.08.43.png

i get this output:

Searching for binary rubies, this might take some time.

No binary rubies available for: osx/10.8/x86_64/ruby-1.9.3-p484.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.

Checking requirements for osx.

Installing requirements for osx.

Updating system
.

Error running 'requirements_osx_port_update_system ruby-1.9.3-p484',
showing last 15 lines of /Users/wdonovan/.rvm/log/1389280127_ruby-1.9.3-p484/update_system.log
[2014-01-09 10:08:47] requirements_osx_port_update_system
requirements_osx_port_update_system () 
{ 
    __rvm_try_sudo port -dv selfupdate || return $?
}
current path: /
PATH=/Users/wdonovan/Dropbox/Enthought/User/bin:/Library/Frameworks/Python.framework/Versions/3.3/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/Users/wdonovan/Desktop/BT2_HOME:/opt/X11/bin:/usr/local/git/bin:/Users/wdonovan/.rvm/bin:/opt/local/bin
command(2): requirements_osx_port_update_system ruby-1.9.3-p484
sudo: no tty present and no askpass program specified
Requirements installation failed with status: 1.

**Comment by wdonovan12** [comment]
oh and i have command line tools installed in xcode

**Comment by remear** [comment]
It's likely requiring your sudo password so it can install the dependencies for the Ruby you want to install. JewelryBox has no support for this yet so you'll have to install dependencies manually or have RVM do it via the command line for now.
