### ISSUE TITLE
Misconfigured SSL cert https://jewelrybox.unfiniti.com/

### ISSUE THREAD

**Issue by mtowers** [remear/jewelrybox#210]
Looks like the SSL cert for the download site is either misconfigured or you got hacked.
![screen shot 2014-03-12 at 10 08 48 am](https://f.cloud.github.com/assets/89975/2400406/1df79cfa-aa0a-11e3-8369-ee443801e537.png)

**Comment by remear** [comment]
We're just in the middle of moving some content around. Pardon our dust for a bit.
