### ISSUE TITLE
RVM Requirement

### ISSUE THREAD

**Issue by designbylefty** [remear/jewelrybox#211]
Each time i go Dashboard > Requirements  i have the same message 

Checking requirements for osx.
Installing requirements for osx.
Updating system.....
Installing required packages: automake, libtool, pkg-config, gcc46, libyaml, readline, libksba, openssl...

and nothing, the first time i say myself there should be a lot to compile so il let my machine turn for 18 hours or something. but no error message no success message but every time i click on Requirement i have the same texte as above. i run osx 10.9

**Comment by remear** [comment]
What package manager are you using? homebrew, port, fink,...?

**Comment by designbylefty** [comment]
sorry my dev env was corrupted, i had to put a lot folders in trash (too much for the system, i had to reinstall it) then i reinstall all my env dev in a clean env and its works  x_X  sorry again
