### ISSUE TITLE
Crashes on launch - 10.7.1

### ISSUE THREAD

**Issue by tsykoduk** [remear/jewelrybox#24]
Able to repro launching from desktop and applications folder.

Machine is a upgrade from 10.6 to 10.7 if that helps.

---

Process:         JewelryBox [48326]
Path:            /Users/USER/Desktop/JewelryBox.app/Contents/MacOS/JewelryBox
Identifier:      com.unfiniti.JewelryBox
Version:         1.0.1 (2806)
Code Type:       X86-64 (Native)
Parent Process:  launchd [299]

Date/Time:       2011-08-25 13:29:03.251 -0700
OS Version:      Mac OS X 10.7.1 (11B26)
Report Version:  9
Sleep/Wake UUID: FD6B57A4-6834-4DBD-BE4A-58A04EA977F2

Interval Since Last Report:          208051 sec
Crashes Since Last Report:           2
Per-App Interval Since Last Report:  31 sec
Per-App Crashes Since Last Report:   2
Anonymous UUID:                      C45532C4-0A3B-4014-AD8B-F0918A9F150F

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
objc[48326]: garbage collection is OFF
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'launch path not accessible'
**\* First throw call stack:

**Comment by remear** [comment]
This is likely due to system-wide installations not being supported. Looking into fixing that support. I'll let you know what I find.

**Comment by remear** [comment]
No longer crashes on launch.
