### ISSUE TITLE
Download the software - website

### ISSUE THREAD

**Issue by jfrolich** [remear/jewelrybox#35]
Is it me or is the download link missing on the homepage, is it a private beta, or is it simply not available in the app-store in Europe.

The copywriting is a bit confusing, because it lists the linux version "under development", implying that the mac version is released. Also there is a bit of text about "The core feature set has the main focus for the next major releases of JewelryBox", implying there is already a major release.

It would be less confusing if you could give pointers about how to install (or information that it is not yet released) on the website.

I would like to try this tool, looks great! :)

**Comment by remear** [comment]
I apologize for the confusion. At that time JewelryBox had not yet been released. Version 1.0 is available for download now. http://jewelrybox.unfiniti.com

Enjoy!
