### ISSUE TITLE
RVM was not detected, but it is.

### ISSUE THREAD

**Issue by larstobi** [remear/jewelrybox#39]
I just downloaded and installed JewelryBox and upon first run, I get this message: "RVM was not detected. To perform a single-user installation of RVM, click Install." However, I have RVM installed.

OS X Lion
/Users folder by MacZFS
rvm version 1.8.3

**Comment by remear** [comment]
Can you provide me with the following:

Shell you use
Output of :  which rvm
Contents of your ~/.rvmrc (if you have one)

**Comment by larstobi** [comment]
GNU bash, version 4.2.10(2)-release (i386-apple-darwin10.7.0)

```
$ which bash 
/opt/homebrew/bin/bash

$ which rvm
/Users/larstobi/.rvm/bin/rvm

$ cat .rvmrc 
export rvm_path="/Users/larstobi/.rvm"
```

**Comment by remear** [comment]
I suspect it's because we resorted to supporting only the stock bash 3 located in /bin/bash. Time constraints =/  Odd though that /opt/homebrew/bin/bash seems to not be picking up your profile script(s) in ~/

Can you provide the output of the following:

/bin/bash -l -c -i "type rvm | head -1"
/bin/bash -l -c -i "which rvm"

**Comment by larstobi** [comment]
```
$ /bin/bash -l -c -i "type rvm | head -1"
rvm is a function
$ /bin/bash -l -c -i "which rvm"
/Users/larstobi/.rvm/bin/rvm
```

**Comment by remear** [comment]
Do you use IRC? We can resolve this faster if you're able to swing by #rvm in irc freenode

**Comment by larstobi** [comment]
Yes, my nick is larstobi there as well. :)

**Comment by asaaki** [comment]
What was the result/solution of this issue? 'cause I've the same issue.

**Comment by larstobi** [comment]
We didn't find the cause yet, but remear is working on it.

**Comment by remear** [comment]
i've been waiting for larstobi to stop by again on IRC. The only way to really solve this problem is to run a debug version of JewelryBox on your machines and see what's happening with commands vs what's expected.

asaaki, are you using .bashrc too or .profile/.bash_profile?

**Comment by asaaki** [comment]
Okay, I played a little bit around.

JB will find the rvm when I used the .bash_profile option to source the rvm env.

The .profile and the .bashrc option won't work (for me), although everything is sourced into the others (so I thought Mac OSX will be able to find and use all shell related stuff which seems not true for JB).

**Comment by larstobi** [comment]
I can confirm that it works when I move 

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
```

from .bashrc to .bash_profile.

**Comment by remear** [comment]
OS X does not auto load .bashrc for most interactive shells, which is what JB needs to use to inherit your user profile ($PATH, exports, etc...) so it can interact with RVM. You can still use .bashrc for everything, it just has to be sourced from either ~/.profile or ~/.bash_profile. Try adding [ -r $HOME/.bashrc ] && source $HOME/.bashrc to ~/.profile or ~/.bash_profile and see if that allows you to launch JewelryBox. I'd also like it if you could swing by #rubunity or #rvm on Freenode IRC so you can also try the latest build. I've fixed a few issues that resolve some other (possibly related) .bashrc issues.

For more information take a look at this interesting article. http://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

**Comment by asaaki** [comment]
My problem was, that I forgot the $HOME var, I really expected an intelligent operating system (finding files in same folder)!!! My fault! ;o)

**Comment by remear** [comment]
asaaki, all systems go now?

**Comment by larstobi** [comment]
When using $HOME/.bashrc, it works here as well.
