### ISSUE TITLE
JewelryBox quit unexpectedly upon app launch

### ISSUE THREAD

**Issue by keilmillerjr** [remear/jewelrybox#43]
I downloaded and installed JewelryBox via the package installer. JewelryBox unexpectedly upon app launch. I can't get the app to launch. I restarted and had no luck.

Mac 10.7.1
rvm 1.6.31
JewelryBox 1.0

In the mean time until this issue gets resolved, how can I safely and cleanly remove the app from my computer? The package installer does not seem to uninstall it as well. I assume a package installer was used because it installs files in various locations or modifies other files... otherwise you could have just compressed the app itself in a zip or dmg file.

Thanks,

Keil

**Comment by remear** [comment]
The package installer only places JewelryBox.app in /Applications. No other files are created in any other location on your machine except ~/.rvm where you install RVM, gemsets, and rubies. To uninstall JewelryBox.app, simply delete it from /Applications.

We won't be able to solve the issue you have without working directly with you. JewelryBox does require RVM 1.8.3 to run because an important fix for OS X was introduced on that version. In the case you have < 1.8.3, you should be prompted by JewelryBox to upgrade your RVM right through the application. But it seems you don't even make it that far. I've installed RVM 1.6.31 and JewelryBox is launching fine and is launching fine on numerous other machines so we need to track down specifically why it isn't on yours.

If you're able to drop by #rvm or #rubunity on IRC free node I can work with you to resolve the issue ASAP. If I don't respond immediately, hang around. I'll respond when I can. (My apologies for responding somewhat slow to this. My iMac died over the weekend and has to be repaired =(  )

The following additional information will help in the meantime:

Output of:
   which rvm
   echo $SHELL
   `echo $SHELL --version`          #the ` are important

**Comment by keilmillerjr** [comment]
Thank you for your reply. I get worried with installers as sometimes its used to install files in erratic places like windows (adobe).

Deleted JewelryBox and jewelrybox.plist
Upgraded rvm via terminal to 1.8.4 (current)
Installed JewelryBox 1.0 again
Immediate crash

I logged and saved my crash report.
https://gist.github.com/c3b8b19bae963d6e883e

I hope I can help you resolve this issue because jewelry box looks cool!

**Comment by remear** [comment]
Do you have the output for those commands? That would help a lot with preliminary troubleshooting.

Also, the output of  git --version

**Comment by keilmillerjr** [comment]
Thank you mac 10.7 for the auto window restore feature!

---

Keils-iMac:keilmiller keiljr$ rvm -v

rvm 1.6.31 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

Keils-iMac:keilmiller keiljr$ rvm get latest

Original installed RVM version:

rvm 1.6.31 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

rvm-1.8.4
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  901k  100  901k    0     0   378k      0  0:00:02  0:00:02 --:--:--  396k

  RVM:  Shell scripts enabling management of multiple ruby environments.
  RTFM: https://rvm.beginrescueend.com/
  HELP: http://webchat.freenode.net/?channels=rvm (#rvm on irc.freenode.net)

Installing RVM to /Users/keiljr/.rvm/
    Correct permissions for base binaries in /Users/keiljr/.rvm/bin...
    Copying manpages into place.

  Notes for Darwin ( Mac OS X Server )
    For Snow Leopard be sure to have Xcode Tools Version 3.2.1 (1613) or later
    You should download the latest Xcode tools from developer.apple.com.
      (This is since the dvd install for Snow Leopard contained bugs).

```
If you intend on installing MacRuby you must install LLVM first.
If you intend on installing JRuby you must install the JDK.
If you intend on installing IronRuby you must install Mono
  (version 2.6 or greater is recommended).

To use an RVM installed Ruby as default instead of the system ruby:
rvm install 1.8.7 # installs patch 352: closest supported version
rvm system ; rvm gemset export system.gems ; rvm 1.8.7 ; rvm gemset import system # migrate your gems
rvm --default 1.8.7
```

NOTE:
As of 1.8.0 RVM once again loads .rvmrc files, by default, after asking your
permission to trust it of course.  If you do not wish to be enabled, simply set:
    export rvm_project_rvmrc=0
Within either your /etc/rvmrc or $HOME/.rvmrc file. This will turn off the
cd/pushd hooks when sourcing the rvm() function into your shell.

 Example: echo 'export rvm_project_rvmrc=0' >> $HOME/.rvmrc;
 (Then close the current shell and open a new one.)

  You must now complete the install by loading RVM in new shells.

  If you wish to use RVM in an interactive fashion in your shells then
  Place the following line at the end of your shell's loading files
  (.bashrc or .bash_profile for bash and .zshrc for zsh),
  after all PATH/variable settings:

  [[ -s "/Users/keiljr/.rvm/scripts/rvm" ]] && source "/Users/keiljr/.rvm/scripts/rvm"  # This loads RVM into a shell session.

  You only need to add this line the first time you install RVM.

  If you are choosing to source RVM into your environment to switch current
  shell environments, be sure to close this shell and open a new one so that
  the RVM functions load.

Installation of RVM to /Users/keiljr/.rvm/ is complete.

Keil Miller Jr,

If you have any questions, issues and/or ideas for improvement please
fork the project and issue a pull request.

If you wish to disable the project .rvmrc file functionality, set
rvm_project_rvmrc=0 in either /etc/rvmrc or ~/.rvmrc.

Thank you for using RVM!

I sincerely hope that RVM helps to make your life easier and more enjoyable!!!

  ~Wayne

Installed RVM version:

rvm 1.8.4 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

Keils-iMac:keilmiller keiljr$ rvm -v

A RVM version 1.8.4 is installed yet 1.6.31 is loaded.
 Please do one of the following:
- 'rvm reload'
- open a new shell

Keils-iMac:keilmiller keiljr$ rvm reload
RVM reloaded!
Keils-iMac:keilmiller keiljr$ rvm -v

rvm 1.8.4 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

**Comment by keilmillerjr** [comment]
Keils-iMac:keilmiller keiljr$ git --version
git version 1.7.4.4

**Comment by remear** [comment]
What file are you using to source RVM? .profile, .bash_profile, .bashrc, .zshrc ...?

What shell are you using?

Looks like a single-user install. Is that correct?

**Comment by keilmillerjr** [comment]
.bashrc
terminal
single-userinstall

I'm tuscanidream on irc channel for a few if you would like to chat there.

**Comment by remear** [comment]
I'll be on IRC for most of today if you have time to work through this.

**Comment by keilmillerjr** [comment]
OK

**Comment by remear** [comment]
This issue was caused by the rvm source line being located in /etc/bashrc. Moving the rvm sourcing line into the user's choice of ~/.profile, ~/.bash_profile, or ~/.bashrc solved the problem.

If the user chooses to use ~/.bashrc, they must also load ~/.bashrc from ~/.profile or ~/.bash_profile.

**Comment by keilmillerjr** [comment]
One last note:

~/.profile, ~/.bash_profile, and ~/.bashrc did not exist with my clean install of mac 10.7 and upgraded to 10.7.1.

I created ~/.profile and inserted the rvm line, and all worked out well with the cosmos.

**Comment by remear** [comment]
Thanks tuscanidream. Enjoy!
