### ISSUE TITLE
Multi-User Installations

### ISSUE THREAD

**Issue by remear** [remear/jewelrybox#44]
Support multi-user installations.

This has been slightly delayed due to permission inconsistencies.

**Comment by jsmestad** [comment]
Definitely something I would love to see :) +1

**Comment by RobertDeRose** [comment]
Here here.  my rvm install is located in /usr/local/rvm as well and Jewelry Box just seems to think I don't have RVM installed.

**Comment by remear** [comment]
/usr/local/rvm is where multi-user installations usually go. As it says on the download page under release notes, multi-user installations are not supported. Plans are in the works to bring multi-user support to JewelryBox but it requires a lot of work to make sure it functions correctly at an enterprise level.

**Comment by mpapis** [comment]
+1 this is important for RIX as it uses multi user installation

as a note also it is already supported but not enabled - I can enter each screen and I was able to install 1.8.7 using JB !

**Comment by remear** [comment]
Multi-user installations should now be supported.
