### ISSUE TITLE
Launch on Startup

### ISSUE THREAD

**Issue by remear** [remear/jewelrybox#48]
Add a preference to launch JewelryBox on login.

**Comment by ghost** [comment]
You can already do this for any app: Start the app, right-click the app in the dock, open Options and choose Open at Login. There's no need to duplicate OS functionality.

**Comment by remear** [comment]
Yes, it can be done from there. Some people have asked for the ability to do it from the preferences view in the application. I'm still trying to determine if that's really necessary.

**Comment by remear** [comment]
Deemed unnecessary since it's easy enough to enable launch on startup from the dock icon.
