### ISSUE TITLE
error seeing gemsets, etc. (WARN: rvm gem  alias to  rvm do gem)

### ISSUE THREAD

**Issue by megatux** [remear/jewelrybox#50]
Hi, first time user. I installed Jewelrybox today. Updated rvm from there (nice!) but there is a warning that bothers some functions and break others:
## msg: 

WARN: Please note that 'rvm gem ...' is only an alias to 'rvm do gem ...' ,
it may work differently as in early versions of RVM and will be shortly removed!

.....here comes the list of gem.....

---

rvm version: 1.8.6 

I can attach an screenshot if necessary.
Thanks a lot!
  Cristian

**Comment by remear** [comment]
The latest rvm (head) has deprecated the exec method in favor of do. I'll be releasing a new version of JewelryBox soon, hopefully this week, to resolve this issue and add new features.

**Comment by megatux** [comment]
Thanks! awaiting their arrival, anxiously :)

**Comment by remear** [comment]
Sorry for the delay. My hard drive died shortly after the 1.0 release and i found out last week that my private key for signing releases to send out over automatic updates was not backed up. I thought it was in a folder with the same name in my projects area and it was in my downloads folder. So this will need to be a manual update. =(   My sincere apologies. Not the end of the world, but I'm not happy about it.
