### ISSUE TITLE
Does not correctly install RVM on fresh Lion install

### ISSUE THREAD

**Issue by cowboyd** [remear/jewelrybox#54]
With a brand new Lion system, I tried to install rvm with jewelry box.

It did not complain, but then when it came to adding lines to my .profile it failed saying "no rvm installation found"

**Comment by remear** [comment]
Is git installed on your machine?

**Comment by cowboyd** [comment]
No, me being silly. I installed the Xcode installer from the app store, but didn't actually run it (I thought it would do it for me)

**Comment by cowboyd** [comment]
(the error message could probably have been better though)

**Comment by remear** [comment]
You are correct. Issue #42 exists to address this problem. While it's not entirely JewelryBox's responsibility to install git for you, I think we need to implement a preflight check to make sure you at least have git installed to guard against this problem.

**Comment by remear** [comment]
Please also note that the current version of Xcode in the App Store is 4.2 and uses LLVM instead of the standard gcc included with 4.1 and older. The RVM team recommends you use
4.1 or older because you'll probably encounter problems installing rubies and gems if you only have 4.2.
