### ISSUE TITLE
Updated RVM via JewelryBox, At least RVM 1.8.3 is required?

### ISSUE THREAD

**Issue by keilmillerjr** [remear/jewelrybox#55]
I'm using the latest version 1.0 of Jewelry Box.

I clicked the Update RVM button within the JewelryBox app.

It nstalled rvm 1.10.0-pre. I can confirm version number via terminal rvm -v that it did install correctly.

JewelryBox won't let me do anything. "! At least RVM 1.8.3 is required to run JewelryBox... Update Now."

Restart app and reboots have no effect on the issue. Any ideas?

Thank you, Keil.

**Comment by unikitty37** [comment]
Progress - I have rvm 1.10-pre and version 1.1.1 of JewelryBox and it now says "At least RVM 1.9.0 is required to run JewelryBox".

It's still not quite worked out that 10 is greater than 9, though :)

**Comment by diablourbano** [comment]
I'm getting the same issue, I'm using rvm 1.10.0-pre but somehow jewerlybox doesn't accept it

**Comment by keilmillerjr** [comment]
@tinyclanger Hmmm... I wasn't aware that there was any newer version of jewelrybox than 1.0! I assume the "check for updates" doesn't work.

Anyways, I upgraded jewelrybox to 1.1.1 via package from website and I get the same issue except now RVM 1.9.0 is required to run JewelryBox.

**Comment by jtmkrueger** [comment]
+1 for this issue.  I'm on jewelrybox version 1.1.1 and being prompted to get RVM version 1.9.0.

**Comment by ghost** [comment]
Ditto, FYI I am stuck in the same loop... JewelryBox comes up but always thinks RVM is missing, even after auto installing it.

**Comment by remear** [comment]
RVM recently changed its versioning schema and started using "pre" and went to 1.10 faster than expected to avoid Ruby confusion between the Ruby versions 1.9.x and RVM 1.9.x. Sorry for this release taking a while to get out. It has big additions and I've come to learn everything takes about 15x longer when you have a newborn child =/  I promise we're working on resolving this as fast as possible.

Feel free to join IRC #rubunity to test beta builds to make sure we get this issue resolved.

**Comment by keilmillerjr** [comment]
Awesome. Thank you for the response and congratulations on the newborn!

Please comment here when the update is out to let followers know. :)

**Comment by remear** [comment]
Fixed in v1.2

**Comment by keilmillerjr** [comment]
Thank you @remear ! All issues seems to have been resolved. :)

**Comment by remear** [comment]
@tuscanidream No problem. Enjoy!

**Comment by unikitty37** [comment]
With 1.2, I just get "rvm is not installed" now. If I click on the "install rvm" button (even though it's working fine from the command line) it says it can't find an rvm sourcing line in my .zshrc, even though it has this at the end:

```
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" # Load RVM function
```

If I tell it to add the line to .zshrc anyway, it then goes back to saying rvm is not installed :(

**Comment by remear** [comment]
@tinyclanger #69 addresses this issue. The fix should arrive in the next day or two.
