### ISSUE TITLE
Program's initial window layout places elements over top of each other

### ISSUE THREAD

**Issue by musaic** [remear/jewelrybox#57]
The first window displayed at program startup (first time use) is "floating" the RVM usage meter over text fields and obscuring OS information.  Re-sizing the window to make it larger corrects the problem since the meter follows the lower window boundary and "pulls" it away from the textual info displayed above it.  Suggest that the dimensions of the window's initial state be increased.

**Comment by remear** [comment]
In order to accommodate smaller display sizes and resolutions, the initial window size cannot be increased. The Dashboard view is being updated to take care of the intersecting areas.

Thanks
