### ISSUE TITLE
JewelryBox thinks 1.10 < 1.9

### ISSUE THREAD

**Issue by eshamow** [remear/jewelrybox#58]
Lion host, RVM 1.10.0-pre - on launch JB thinks it needs to upgrade RVM.  Once it does this (redownloads the existing version) it's happy and can be used, although it freezes again if asked to calculate dependencies, etc.

**Comment by johnste** [comment]
Having this exact issue as well.

**Comment by remear** [comment]
Thinks 1.10 < 1.9 how? If it did, it wouldn't ask you to update. What's the issue here?

If it's the freezing on rvm usage calculations, a shell command is listed in #52 that can be used to circumvent the issue until the next release.

**Comment by johnste** [comment]
Each and every time I launch JewelryBox I get a warning: "At least RVM 1.9.0 is required to run JewelryBox". I click "update" and it "updates" RVM and then I get another notice "RVM installation was successfully updated!".

$ rvm --version

rvm 1.10.0-pre by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

Output of JewelryBox install log (or what I manage to copy before it closes)

Original installed RVM version:

rvm 1.10.0-pre by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

HEAD is now at ad05ef3 command -> _command

  RVM:  Shell scripts enabling management of multiple ruby environments.
  RTFM: https://rvm.beginrescueend.com/
  HELP: http://webchat.freenode.net/?channels=rvm (#rvm on irc.freenode.net)

Installing RVM to /Users/john/.rvm/

**Comment by remear** [comment]
Ah. It's somewhat the same issue being discussed in #55. We're working on resolving it.

Sorry for this release taking a while to get out. It has big additions and I've come to learn everything takes about 15x longer when you have a newborn child.

Feel free to join IRC #rubunity to test beta builds to make sure we get this issue resolved.

**Comment by johnste** [comment]
Thanks for the quick answer! No worries about it taking a bit of time, I'm about to become a dad as well. ;)

**Comment by remear** [comment]
Congrats!

**Comment by remear** [comment]
Fixed in v1.2

**Comment by axcdnt** [comment]
This v1.2 is really, really stable. Thanks man, keep going!
