### ISSUE TITLE
Cannot install RVM through JewelryBox

### ISSUE THREAD

**Issue by paulhuff** [remear/jewelrybox#59]
No matter which option I select: profile, bash_profile, bashrc, zshrc or manual config I get the following error:

"RVM was not detected. Please recheck your configuration."

What am I missing?  I followed this wizard because RVM was not installed and went through the Install button.  So, I cannot continue because RVM is not installed, but cannot install RVM because RVM is not detected? I'm in a quandary.

**Comment by remear** [comment]
Do you have git installed?

**Comment by paulhuff** [comment]
I just went ahead and installed RVM straight from github. Thx anyway.

Sent from my iPhone

On Dec 4, 2011, at 10:42 AM, Ben Mills
reply@reply.github.com
wrote:

> Do you have git installed?
>

**Comment by paulhuff** [comment]
Yes I do.

Sent from my iPhone

On Dec 4, 2011, at 10:42 AM, Ben Mills
reply@reply.github.com
wrote:

> Do you have git installed?
>

**Comment by cpvandermade** [comment]
The problem with my installation was that there was a space in my username of my mac. I fixed it by creating a another user on my mac without spaces and it installed instantly!
