### ISSUE TITLE
RVM updates every time

### ISSUE THREAD

**Issue by YavorIvanov** [remear/jewelrybox#60]
The error is pretty annoying though not critical.

Every time I lunch the app it says that RVM version is too low.
After update everything is fine till I restart the app and then it needs to update RVM again.

This is OS X Lion 10.7.2

**Comment by aneely** [comment]
I'm having the same problem. I think this is related to issue #58.

**Comment by UncleRic** [comment]
1) I'm having the same problem too.... 
   I noticed it just after I donated $s.

2) Also, Wrong Color: the gray icons appear to be 'disabled'.
   Try another hue or shade.

3) Lock the NSWindow.  It doesn't need to re-size.

Otherwise, a good product; worth my donation!

**Comment by remear** [comment]
Duplicate of #58
