### ISSUE TITLE
"Click install" -> there's no install button

### ISSUE THREAD

**Issue by iandundas** [remear/jewelrybox#61]
Unless I'm missing something (likely), there is no install button available when it says "RVM was not detected. To perform a single-user installation of RVM, click Install"

See a screenshot: http://i.imgur.com/S6CFv.png

it's correct that I don't have RVM installed (although it was in the past) and:

$ ruby -v
ruby 1.8.7 (2010-01-10 patchlevel 249) [universal-darwin11.0]

$ git --version
git version 1.7.5.4

Jewelrybox v1.1.1

**Comment by iandundas** [comment]
Just to confirm, none of the toolbar buttons are active either.

**Comment by honnix** [comment]
same problem, any idea? btw, i've got rvm installed to /usr/local, but why it complains not detected.

**Comment by remear** [comment]
@honnix Only single-user installations are supported and ONLY ones in ~/.rvm.

**Comment by honnix** [comment]
@remear ok, thank, then I will come back later after it supports multi-user. :)

**Comment by remear** [comment]
@iandundas I'm still unable to reproduce this on any of my machines running v1.2. Please let me know if this is still an issue after I release v1.2.

**Comment by iandundas** [comment]
Will do. If you want more info on my install just let me know, new to this so not sure what you'd need.

Cheers,
Ian

**Comment by remear** [comment]
@iandundas Would you swing by #rubunity and ping me so I can get you a beta to try?

**Comment by remear** [comment]
@iandundas Is this still an issue in v1.2?

**Comment by iandundas** [comment]
'fraid not:

![Wants me to upgrade](http://i.imgur.com/dOlh5.png)
![Fails to upgrade](http://i.imgur.com/DqphX.png)

$ rvm --version

rvm 1.10.0 by Wayne E. Seguin (wayneeseguin@gmail.com) [https://rvm.beginrescueend.com/]

$ rvm get stable

$ rvm reload
$ rvm --version

rvm 1.10.1 by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.beginrescueend.com/]

After upgrading RVM manually, the app now works.

p.s. sorry for not joining you on IRC, not familiar with how it works & was snowed under this week.
