### ISSUE TITLE
Growl RVM update notifications broken

### ISSUE THREAD

**Issue by remear** [remear/jewelrybox#65]
Growl notifications appear for RVM updates even when latest version == installed version

**Comment by geoffreywiseman** [comment]
I'm seeing this as well.

**Comment by Axiol** [comment]
Yep, me to :)

**Comment by jtmkrueger** [comment]
I'm also seeing this, but not every 5 minutes.  It shows at seemingly random times.

**Comment by remear** [comment]
This should be fixed in v1.2.1. Let me know if it still persists after updating.
