### ISSUE TITLE
Can't install RVM from behind firewall

### ISSUE THREAD

**Issue by michael-groble** [remear/jewelrybox#67]
I see the same behavior and error message listed in issue #59 when I am behind a firewall.  I cant see where to specify a proxy in JewelryBox and it is not using the one from the system configuration.

**Comment by remear** [comment]
There currently isn't a way to configure a proxy through JewelryBox.

Where and how are configuring your proxy?

**Comment by michael-groble** [comment]
I have it configured in the OSX Network System Preferences.

After installing rvm, I had the same proxy problem installing a ruby.  I followed the instructions here http://beginrescueend.com/workflow/proxy/ to set my git and curl defaults appropriately, which solved my problem.  I didn't go back to see if that would also work for getting rvm itself.

**Comment by remear** [comment]
It's been determined configuring a proxy should be handled outside JewelryBox and is considered a prerequisite to installing RVM.
