### ISSUE TITLE
"Update is improperly signed" error when updating to 1.2

### ISSUE THREAD

**Issue by jstr** [remear/jewelrybox#68]
When I try and update to 1.2 through the Sparkle updater I get an error: "Update is improperly signed".

**Comment by remear** [comment]
What version of JewelryBox are you currently running? If you have earlier than 1.1 (I think), you'll probably need to download a new copy from http://jewelrybox.unfiniti.com since that version fixed the automatic update problem.

**Comment by jstr** [comment]
I was using 1.0. I've installed the latest version straight from the site. Thanks!
