### ISSUE TITLE
ZSH Support

### ISSUE THREAD

**Issue by remear** [remear/jewelrybox#7]
Add support for using zsh as the shell to interact with RVM.

**Comment by adamjleonard** [comment]
+1 This is a HUGE needed feature as many of us use zsh!

**Comment by jlecour** [comment]
As a Zsh user, I'd be glad to help.

**Comment by remear** [comment]
What zsh startup file are you both using to source rvm?

**Comment by jlecour** [comment]
I've got :

```
[[ -s "/Users/jlecour/.rvm/scripts/rvm" ]] && source "/Users/jlecour/.rvm/scripts/rvm"  # This loads RVM into a shell session.
```

in my `~/.zshrc` file.

**Comment by remear** [comment]
zsh support is looking nearly complete. I could absolutely use some beta testing. Ping me in #rvm or #rubunity on Freenode IRC if you're interested.

**Comment by remear** [comment]
jlecour, you can file any crash reports by attaching them to this issue. However, no need to post the one you found. I already discovered the problem was due to a typo. Ping me when you're around again and I'll get you another build.

**Comment by remear** [comment]
jlecour, zsh support should now be complete. Ping me in #rubunity when you're around and ready to try out the latest build.
