### ISSUE TITLE
Allow application to run as a menubar only app.

### ISSUE THREAD

**Issue by jtmkrueger** [remear/jewelrybox#70]
This would clear it off my dock, and keep it off my command + tab app changing.

Having a checkbox in the settings to let me include it in the startup items would be gravy, but I can always do that myself.

**Comment by benr75** [comment]
+1

**Comment by reger** [comment]
+1

**Comment by alanbaldwin** [comment]
+1

**Comment by remear** [comment]
This feature has existed since v1.1 but apparently it's broken in v1.2. I just fixed it and you'll see it working again in v1.2.1. 

This setting can be found in Preferences as "Show Icon in Dock"

**Comment by jtmkrueger** [comment]
I don't think this is a fixed, and I also don't know if I would call it a bug.  Apps like Sparrow and Dropbox have an option where they can run as a doc only app or a menu bar only app.  Here's a screenshot from sparrow's prefrences:

http://cloud.jtmkrueger.com/270Y440k0z1r1s0u0T3x

All I'm interested in having is a way to run the app as a menu bar only app.  I would call this a feature request.

Sorry for the confusion, I should have clarified a bit more. I hope this get's reopened.

**Comment by remear** [comment]
This is what that preference already provides. Check the box to show the
application in the Dock, in the application switcher, and in the system
menu bar. Uncheck the box to make it not show in the Application Switcher
or the Dock and only have it in the system menu bar. It's set to show in
the Dock by default. This functionality was added in v1.1, was broken in
v1.2, and is now fixed (or should be) in v1.2.1.

Are you asking for something else to be done?

**Comment by jtmkrueger** [comment]
I see now, guess it was a little unclear to me how that checkbox worked.  

Thanks!

This is exactly what I was asking for.

**Comment by remear** [comment]
Should the wording be improved or perhaps change the checkbox into a drop
down or is it acceptable as-is? Or would maybe an extensive online
documentation area be sufficient?

On Mon, Jan 23, 2012 at 2:14 PM, jtmkrueger <
reply@reply.github.com

**Comment by jtmkrueger** [comment]
I think it's fine.  

That said, some people don't like having thing's in their menu bar so perhaps a drop down ('show icon in:') with options for:

dock and menu bar
dock only
menu bar only

Personally, this would be gravy since I'm comfortable with the current setup.  Others may really appreciate the ability to set it up the way they want though.
