### ISSUE TITLE
I have rvm installed but jewelrybox does not detect it.

### ISSUE THREAD

**Issue by ChasManRors** [remear/jewelrybox#74]
I have rvm installed but jewelrybox does not detect it.

My rvm is a completely fresh install.  I just imploded the last release and have tested it.  Then I installed jb and it does not see the ~/.rvm/

**Comment by remear** [comment]
Please gist the output of ls -la ~/.rvm

In what file are you attempting to source rvm? What shell are you wanting to use for rvm?

Did you use JB to install rvm or was it via the command-line?
