### ISSUE TITLE
Application freezes after double clicking the "Gemsets" icon

### ISSUE THREAD

**Issue by s2k** [remear/jewelrybox#77]
Scenario

The app is installed on a MacBook Air and a Ruby 1.9.3 p0 has been installed.
The Xcode Version is 4.2, the Clang option was used to build Ruby

The "Gemsets" icon is double clicked

Behaviour

The application seems to entirely stop reacting, the beach ball is displayed
It look like the app can only be shut down by using the activity display app (or killing the apps process)

Expectation

No freezing, either there should be now reaction or the same reaction as single clicking the icon

**Comment by remear** [comment]
Also happening with Update area. Likely transition related. Simple solution for now is to not double-click.
