### ISSUE TITLE
Please don't f* with my bash_login, it isn't polite

### ISSUE THREAD

**Issue by mcamiano** [remear/jewelrybox#78]
I'm not sure if it was JewelryBox or the RVM install that did it, but I use a .profile file to set up various settings for terminal shells. 
After installing JewelryBox and (uninstalling and reinstalling) a new version of RVM (the old one failed to update because of what it said were merge conflicts on an outdated install), my system seemed to run fine.  I went to a meeting, and came back. Suddenly nothing is working in my terminal, as if something had removed my rc files. Well, not exactly as it turns out: one of those processes simply added a completely spurious .bash_login that was not present before, forcing bash to ignore the .profile .  

At least, that's what the behavior seems to indicate. I already had the RVM environment set up, so deleting the unnecessary .bash_login file fixed everything. But really, it isn't polite to automagically botch the shell environment like that.

**Comment by esparkman** [comment]
That behavior is news to me when installing JewelryBox. That sounds more like something RVM may have done.

**Comment by mpapis** [comment]
@mcamiano this is behavior of RVM, JB is not involved in this process, @remear please close here. 

@mcamiano please read this https://rvm.beginrescueend.com/support/faq/#shell_login it's current state of RC files in linux systems, RVM will detect that you moved sourcing line from ~/.bash_profile to ~/.profile and will not update it anymore. You can open a [ticket for RVM](https://github.com/wayneeseguin/rvm/issues) but unless you provide a better solution which considers  https://rvm.beginrescueend.com/support/faq/#shell_login I wont be able to do much about it.

**Comment by mcamiano** [comment]
Gotcha. I'm on OSX. Sorry for the trouble ticket. 

On Feb 15, 2012, at 1:41 PM, Michal Papis wrote:

> You can open a [ticket for RVM](https://github.com/wayneeseguin/rvm/issues) but unless you provide a better solution which considers https://rvm.beginrescueend.com/support/faq/#shell_login I wont be able to do much about it.

Mitch Amiano,
President and Sr. Content Integrator
(919)760-0192            http://www.agilemarkup.com

Agile Markup Corporation
Consulting&  Services for Content, Process, and Applications
Authorized Reseller, oXygen XML Editor
Clients including  St. Augustine's College, NCSU E.P.Fitts Coll. of Engineering, Merlin Color, Allied Telesis, Above and Beyond Learning, and more

**Comment by mcamiano** [comment]
It was. Sorry for the trouble. Touching .bash_profile or .bash_login makes .profile invisible to a bash terminal window; which is normal; 

On Feb 15, 2012, at 1:25 PM, Evan Sparkman wrote:

> That behavior is news to me when installing JewelryBox. That sounds more like something RVM may have done.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/remear/jewelrybox/issues/78#issuecomment-3985885

Mitch Amiano,
President and Sr. Content Integrator
(919)760-0192            http://www.agilemarkup.com

Agile Markup Corporation
Consulting&  Services for Content, Process, and Applications
Authorized Reseller, oXygen XML Editor
Clients including  St. Augustine's College, NCSU E.P.Fitts Coll. of Engineering, Merlin Color, Allied Telesis, Above and Beyond Learning, and more

**Comment by mcamiano** [comment]
Nice tool, BTW.

On Feb 15, 2012, at 1:25 PM, Evan Sparkman wrote:

> That behavior is news to me when installing JewelryBox. That sounds more like something RVM may have done.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/remear/jewelrybox/issues/78#issuecomment-3985885

Mitch Amiano,
President and Sr. Content Integrator
(919)760-0192            http://www.agilemarkup.com

Agile Markup Corporation
Consulting&  Services for Content, Process, and Applications
Authorized Reseller, oXygen XML Editor
Clients including  St. Augustine's College, NCSU E.P.Fitts Coll. of Engineering, Merlin Color, Allied Telesis, Above and Beyond Learning, and more
