### ISSUE TITLE
Download from website fails with "file not found"

### ISSUE THREAD

**Issue by fuchsblau** [remear/jewelrybox#81]
Cant't download because of file not found. Is there any other source to get the download from?

**Comment by londospark** [comment]
I can confirm that this is also happening to me.

**Comment by remear** [comment]
My apologies. We're in the process of server migrations. Can you see if it works now?

**Comment by mtheoryx** [comment]
The download worked fine for me today.

**Comment by suprawsm** [comment]
Is there any alternative source where I can find the download? Having trouble downloading it (file not found).

**Comment by remear** [comment]
Has this issue been resolved for any of you yet? If not, please provide the results of ping and nslookup unfiniti.com and jewelrybox.unfiniti.com.

**Comment by londospark** [comment]
It's just worked for me as well thanks.

**Comment by suprawsm** [comment]
Same here, I just got it.. Thanks.

**Comment by remear** [comment]
Sorry for the downtime. The old DNS host held onto entries it shouldn't have. Yak successfully shaved.

Thanks for using JewelryBox!

**Comment by mtheoryx** [comment]
Yep, working fine now.
