### ISSUE TITLE
Can't update JewelryBox

### ISSUE THREAD

**Issue by mtheoryx** [remear/jewelrybox#83]
"Improperly signed update" dialogue box comes up with the only option to "cancel update".

Current version I'm on:

http://bit.ly/wbXbN4

**Comment by remear** [comment]
The updated was fixed in version 1.1. You'll have to manually download the application again from http://jewelrybox.unfiniti.com

The current version is 1.2.1. It should have some much better additions and allow you to use RVM 1.10.3.

**Comment by mtheoryx** [comment]
You're right. Issue resolved, and wow, so many new features!!

**Comment by remear** [comment]
Wait till the release of 1.3   >8)

**Comment by mtheoryx** [comment]
Well, I don't know if I can take much more awesomeness... still adjusting to this version. Love the addition of info in the menubar! That is really useful.

**Comment by remear** [comment]
Thanks. Feature requests are always welcome.

**Comment by limratana** [comment]
I'm having this problem upgrading to 1.4.1 from 1.3.

**Comment by HughGrant** [comment]
same problem with upgrading, my current version is 1.3 build 2156

**Comment by remear** [comment]
@limratana, @HughGrant The easiest thing will be for you to download the latest version from the site.
