### ISSUE TITLE
add support for .ruby-version / .versions.conf

### ISSUE THREAD

**Issue by mpapis** [remear/jewelrybox#84]
Hi,

Please add support for additional project configuration files described here: https://gist.github.com/1912050#gistcomment-86575

Both work without authentication of the file:
- `.ruby-version` - only ruby version, rvm supports `@gemset` but is discouraged for compatibility with other tools
- `.versions.conf` - similar functionality to `.rvmrc` but is fixed format not allowing to mess system environment - those it's safer

**Comment by mpapis** [comment]
more details after discussion in irc:

a list could be found by checking user projects dir (everybody has one):

```
find ~/projects/ -maxdepth 3 -type f \( -name .rvmrc -or -name .versions.conf -or -name .ruby-version \)
```

I used `~/projects/` as most possible place to store projects.

you could 
- allow converting between different file formats
- editing project configuration
- upgrading rubies: `rvm upgrade 1.9.3-p0 1.9.3-p125` and automatically updating project file.
- validating that it works (open subshell, `cd  /project/path` and check if it ended with proper ruby listed in the file)

**Comment by remear** [comment]
This requires JewelryBox to introduce project management features. More discussion on this is required.

**Comment by ringods** [comment]
A minimal action to support is to right-click on a gemset and have an action available to generate `.ruby-version` and `.ruby-gemset` into a folder that I can select.
