### ISSUE TITLE
Fix dead link on official website

### ISSUE THREAD

**Issue by mtheoryx** [remear/jewelrybox#85]
If you do a search for "rvm jewelrybox", the very top result is a 404:

http://unfiniti.com/software/mac/jewelrybox

The second result, which works, is:

http://jewelrybox.unfiniti.com/

You might consider doing a simple 301 redirect from the top one to the second one. Cheers!

**Comment by remear** [comment]
They're actually two entirely different pages. We're undergoing server migrations and I wonder if DNS is still incorrect. Could you ping unfiniti.com and jewelrybox.unfiniti.com and tell me what IPs it's giving you for each.

**Comment by mtheoryx** [comment]
I get 71.195.212.148 for both right now.

**Comment by esparkman** [comment]
Both links seem to be working fine for me.

**Comment by mtheoryx** [comment]
The first one is still down for me. Might be temporary though.

http://i.imgur.com/cqMHL.png

**Comment by remear** [comment]
@mtheoryx Interesting, those are the right IPs. Does it work if you specifically put www. in the url?

**Comment by mtheoryx** [comment]
Yep, does work with 'www' prepended.

**Comment by remear** [comment]
@mtheoryx Does it work without 'www' yet?

**Comment by mtheoryx** [comment]
Yep, good to go. Thanks!

**Comment by anamba** [comment]
This doesn't work for me, it's because of this:
unfiniti.com has IPv6 address ::1

Thus, I get a routing error from my local Rails install.

**Comment by remear** [comment]
@anamba Can you hop in #rubunity on free node IRC and chat with me while I work on this?
