### ISSUE TITLE
Error fetching source

### ISSUE THREAD

**Issue by sylvaincarle** [remear/jewelrybox#86]
When trying to install, I get this error message:

ruby-1.9.3-head - #fetching 
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions

How can I fix that, it looks like it could be easy to add the missing "-" to the path… but I can't find where.

**Comment by sylvaincarle** [comment]
Using OSX 10.7.3

**Comment by remear** [comment]
Head is the live in-progress branch for 1.9.3 and they're constantly committing to it. For whatever reason, the source tree gets messed up so it things there is no HEAD revision. They usually fix it after a bit.
