### ISSUE TITLE
updates not working

### ISSUE THREAD

**Issue by mtheoryx** [remear/jewelrybox#87]
Clicking "Check for updates" results in this:

http://i.imgur.com/uzx3z.png

**Comment by remear** [comment]
@mtheoryx is this issue resolved now that our DNS migration seems to be complete?

**Comment by mkuzmin** [comment]
yes, I experienced the same issue, and now it has been resolved.

**Comment by mtheoryx** [comment]
Yes, it appears to be resolved. Thanks!
