### ISSUE TITLE
Picking up different GCC location

### ISSUE THREAD

**Issue by dashdotat** [remear/jewelrybox#88]
On a fresh install of Lion (10.7) with Xcode installed /usr/bin/gcc is the LLVM version - I've installed osx-gcc-installer and installed GCC 4.2 as /usr/bin/gcc-4.2 and /usr/bin/g++-4.2 - I've exported CC and CXX to the correct paths in my ~/.bash_profile and RVM from the command line works OK, however after logging out, restarting etc. JewelryBox still seems to only detect /usr/bin/gcc and fails to install any Rubies - can JeweleryBox honour CC/CXX if set, or let users give a path to the GCC to use in the Preferences pane?

**Comment by dashdotat** [comment]
Sorry, just re-tested and Ruby does install via JewelryBox however the System Information page doesn't point to the GCC which is going to be used to install

**Comment by remear** [comment]
Have you tried putting those CC options in the Compile Flags field in the ruby installation options pane?

And have you tried checking the "Use Clang" box?

**Comment by remear** [comment]
To accurately see those settings in JewelryBox, they'd need to be set from your shell profile. Version 1.3 should now be inheriting the bash environment for the GCC version check. That's the best I can do at present since RVM uses custom detection and those methods are not exposed publicly.
