### ISSUE TITLE
preference "default shell to use for RVM interface" not working

### ISSUE THREAD

**Issue by ghost** [remear/jewelrybox#89]
The preference "default shell to use for RVM interface" is not working. Defaults to bash every time JewelryBox is closed and reopened.

**Comment by remear** [comment]
The shell drop down is slated for removal from v1.3 since the shell is automatically detected on application launch based on where RVM is being sourced.

Do you see a reason to keep it around?

**Comment by remear** [comment]
Removed in v1.3 since the shell will be automatically detected.
