### ISSUE TITLE
Bison?  Jewelry box 1.2.1

### ISSUE THREAD

**Issue by egandrew** [remear/jewelrybox#95]
I've installed jewelry box 1.2.1 after I found it going thru the rails tutorial.  I picked Ruby 1.9.2 to install and it failed saying I needed 'Bison'.  What's that.  I'm new to Mac OSX and will google around.  I was just surprise the Jewelry box didn't offer tips on solving that issue.

**Comment by remear** [comment]
Do you have Xcode or os-x-gcc-installer installed? That is a perquisite for RVM.

**Comment by egandrew** [comment]
THanks.  I'm on a steep learning curve.  I've deciphered that this means I don't have Xcode installed.  On top of that I need an old version 4.1 instead of the latest 4.3.2...so I had to find my want into the apple developer center.
I appreciate the human-outreach remear. 
I'm hoping that, per other comment from folks, that 4.1 has these utilities, whereas I read the newer version is missing expected functions and some Ruby installations fail from JewelryBox.
-A

**Comment by remear** [comment]
Happy to help. The "Release Notes" area accessible via the JewelryBox dashboard will explain what you need to know about getting up and going with RVM on OS X. Feel free to swing by IRC Freenode #rubunity or #rvm for more assistance.

Please be aware that JewelryBox was released with RVM 1.10.0 and is now at 1.11.3. There are known issues JewelryBox has with newer versions of RVM and I'm working to fix them in v1.3.
