### ISSUE TITLE
jewelrybox provides poor feedback while removing rubies

### ISSUE THREAD

**Issue by jonah-williams** [remear/jewelrybox#96]
I installed jewelrybox 1.2.1 build 875 and used it to clean up a number of old rubies on my system.

When I select "Remove" in the overview tab for a ruby 1.8.7 install and saw the "removing" label. I then selected a 1.9.2 ruby and then returned to the 1.8.7 install which was being removed. Now I see the overview tab for the 1.8.7 install and no hint if it is in the process of being removed, has been removed, or if the remove has been cancelled and if so if the ruby is in a valid state or not. Eventually the ruby disappears but I was able to queue up a number of rubies for removal and then had no idea (short of watching console log statements) if jewelrybox was actually working, failed, or idle.

I also appear to be able to start removing a ruby again during this process and have no idea what would result from such an action.

**Comment by remear** [comment]
Took almost a year to get to this. Embarrassing, I apologize. The Ruby removal experience should now be much improved. Expect this in v1.5.
