### ISSUE TITLE
user/db ignored?

### ISSUE THREAD

**Issue by rebx** [remear/jewelrybox#97]
Hi,

It seems like jewelrybox is ignoring the settings in $rvm_path/user/db when I install a (new) (c)Ruby. For example, I have 

<pre>
cat $rvm_path/user/db
# User settings, overrides db settings and persists across installs.
--with-readline=$rvm_usr_path --with-iconv-dir=$rvm_usr_path --with-zlib-dir=$rvm_usr_path --with-openssl-dir=$rvm_usr_path --with-mysql-dir=/usr/local/mysql
</pre>

so it compiles rubies properly with the readline, iconv, zlib libs installed via `rvm pkg install [foo]`

Is there a setting that replaces that, or does it not reference those settings?

**Comment by remear** [comment]
Those settings should be respected. JewelryBox doesn't do anything special with settings or the env. It's possible the format of the command based on the options you choose in the ruby installation options could affect this. Are your settings applied correctly when you try the same thing from the command-line?

**Comment by rebx** [comment]
yep, I can confirm that they do. I guess I'll just use the command line for now...
