### ISSUE TITLE
updates & startup

### ISSUE THREAD

**Issue by phildobbin** [remear/jewelrybox#98]
I've disabled automatically check for updates in Prefs but JewelryBox still goes ahead & tells me when there's updates available.

Also on re-boot I've chosen to hide it at startup in Apple Sys Prefs but it springs to the front & takes a good couple of minutes to determine the machine state which clogs startup.

All this on OS X 10.6.8, latest rvm on a Macbook Pro...

**Comment by remear** [comment]
I just fixed the update checking so it can be enabled/disabled properly. It will be released with v1.3.

As for the hiding at startup, I'll have to look into what's possible to even do about it.

**Comment by phildobbin** [comment]
thanks. Sometimes I think Wayne & Michal work too hard. They release two, three updates a day :-)
